ingress:
  ingressClassName: nginx

#persistence:
#  storageClassName: hostpath

mariadb:
  enabled: true
  auth:
    rootPassword: "mmli"
    password: "mmli"
    username: "mmli"
    database: "mmli"
