ingress:
  ingressClassName: nginx
  hostname: jobmgr.localhost

persistence:
  storageClassName: hostpath

mariadb:
  enabled: true
  auth:
    existingSecret: ""
    rootPassword: "mmli"
    password: "mmli"
    username: "mmli"
    database: "mmli"
