ingress:
  hostname: jobmgr.localhost

controller:
  image: moleculemaker/mmli-job-manager:dev

persistence:
  # Set this to use a particular StorageClass
  # Unset this to use a clsuter default StorageClass
  storageClassName: ""

mariadb:
  enabled: true
  auth:
    existingSecret: ""
    rootPassword: ""
    password: ""
    username: ""
    database: ""
