---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uws-working-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-sc-retain
